[server]
	port=8080
	debug=true

[client]
	username="teemant"
	realname="A Teemant User"
	default_quit_msg="Teemant IRC"
	default_part_msg="Bye!"
	secure_by_default=false
	timeout=3000
	encoding="utf-8"
	rejectUnauthorizedCertificates=false
